In [1]:
!pip install tensorflow

    100% |████████████████████████████████| 44.1MB 11kB/s 
    100% |████████████████████████████████| 61kB 68kB/s 
    100% |████████████████████████████████| 5.6MB 100kB/s 
    100% |████████████████████████████████| 102kB 31kB/s 
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [20]:
# set keras backend to use the theano library
!KERAS_BACKEND=theano python -c "from keras import backend"

Using Theano backend.


In [6]:
from keras import backend as K
input_ = K.placeholder((2,2,2))
print(input_)

/placeholder


In [10]:
var = K.zeros((2,2,2))
print(type(var))

<class 'theano.tensor.sharedvar.TensorSharedVariable'>


In [15]:
print K.backend()

theano


In [16]:
var

/variable

In [17]:
var.eval() # returns the value inside the variable

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]]], dtype=float32)

In [18]:
var._keras_shape # return the shape of keras variable

(2, 2, 2)

In [19]:
var

/variable

In [20]:
var.dtype

'float32'

In [21]:
var.eval() # same as below

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]]], dtype=float32)

In [22]:
K.eval(var) # same as above

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]]], dtype=float32)

In [26]:
import numpy as np
x = K.variable(np.array([[2,3], [6,9]]), dtype='float32')
y = K.variable(np.array([[1,2], [6,1]]), dtype='float32')

In [29]:
z = K.dot(x,y) # performs simple matrix multiplication
print(x.eval())
print(y.eval())
print(z.eval())

[[ 2.  3.]
 [ 6.  9.]]
[[ 1.  2.]
 [ 6.  1.]]
[[ 20.   7.]
 [ 60.  21.]]
